# Generated by Django 5.1.4 on 2025-06-08 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Road_Segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='roads.roadsegment')),
            ],
        ),
    ]
